INSERT INTO Company(c_id, c_name) VALUES (1, '1password');
INSERT INTO Company(c_id, c_name) VALUES (2, 'Abbott ADD');
INSERT INTO Company(c_id, c_name) VALUES (3, 'Abnormal Security');
INSERT INTO Company(c_id, c_name) VALUES (4, 'Accedo');
INSERT INTO Company(c_id, c_name) VALUES (5, 'Achievers inc');
INSERT INTO Company(c_id, c_name) VALUES (6, 'Addepar');
INSERT INTO Company(c_id, c_name) VALUES (7, 'ADP');
INSERT INTO Company(c_id, c_name) VALUES (8, 'AGF');
INSERT INTO Company(c_id, c_name) VALUES (9, 'AI Arena');
INSERT INTO Company(c_id, c_name) VALUES (10, 'Akuna Capital');
INSERT INTO Company(c_id, c_name) VALUES (11, 'Altice USA');
INSERT INTO Company(c_id, c_name) VALUES (12, 'Amazon');
INSERT INTO Company(c_id, c_name) VALUES (13, 'AMD');
INSERT INTO Company(c_id, c_name) VALUES (14, 'American Express');
INSERT INTO Company(c_id, c_name) VALUES (15, 'ANSYS');
INSERT INTO Company(c_id, c_name) VALUES (16, 'Apple');
INSERT INTO Company(c_id, c_name) VALUES (18, 'Arctic Wolf');
INSERT INTO Company(c_id, c_name) VALUES (19, 'Aterlo Networks');
INSERT INTO Company(c_id, c_name) VALUES (20, 'Athelas');
INSERT INTO Company(c_id, c_name) VALUES (21, 'Athos');
INSERT INTO Company(c_id, c_name) VALUES (22, 'Atolio');
INSERT INTO Company(c_id, c_name) VALUES (23, 'ATS Corporation');
INSERT INTO Company(c_id, c_name) VALUES (24, 'Autodesk');
INSERT INTO Company(c_id, c_name) VALUES (26, 'Autonomic');
INSERT INTO Company(c_id, c_name) VALUES (27, 'Axonify');
INSERT INTO Company(c_id, c_name) VALUES (28, 'Bank of America');
INSERT INTO Company(c_id, c_name) VALUES (29, 'Bank of Montreal');
INSERT INTO Company(c_id, c_name) VALUES (30, 'BDO');
INSERT INTO Company(c_id, c_name) VALUES (31, 'Bentley Systems');
INSERT INTO Company(c_id, c_name) VALUES (32, 'BetterUp');
INSERT INTO Company(c_id, c_name) VALUES (33, 'Bitbuy');
INSERT INTO Company(c_id, c_name) VALUES (34, 'Bitgo (Lumina)');
INSERT INTO Company(c_id, c_name) VALUES (35, 'Blackberry');
INSERT INTO Company(c_id, c_name) VALUES (36, 'bld.ai');
INSERT INTO Company(c_id, c_name) VALUES (37, 'Bloomberg');
INSERT INTO Company(c_id, c_name) VALUES (38, 'Bloq');
INSERT INTO Company(c_id, c_name) VALUES (39, 'Bluescape');
INSERT INTO Company(c_id, c_name) VALUES (40, 'Bolt');
INSERT INTO Company(c_id, c_name) VALUES (41, 'Bonfire Interactive');
INSERT INTO Company(c_id, c_name) VALUES (42, 'Boosted.AI');
INSERT INTO Company(c_id, c_name) VALUES (43, 'Borrowell');
INSERT INTO Company(c_id, c_name) VALUES (44, 'Brookfield Annuity');
INSERT INTO Company(c_id, c_name) VALUES (45, 'Brookfield Renewables');
INSERT INTO Company(c_id, c_name) VALUES (46, 'C.E. McMahon Professional Corporation');
INSERT INTO Company(c_id, c_name) VALUES (47, 'CAAT Pension Plan');
INSERT INTO Company(c_id, c_name) VALUES (48, 'Canadian Food Inspection Agency');
INSERT INTO Company(c_id, c_name) VALUES (49, 'Canix');
INSERT INTO Company(c_id, c_name) VALUES (50, 'Capco');
INSERT INTO Company(c_id, c_name) VALUES (51, 'Capital1');
INSERT INTO Company(c_id, c_name) VALUES (52, 'Carfax (Dev)');
INSERT INTO Company(c_id, c_name) VALUES (53, 'Carta');
INSERT INTO Company(c_id, c_name) VALUES (54, 'Castleton Commodities');
INSERT INTO Company(c_id, c_name) VALUES (55, 'CEGN');
INSERT INTO Company(c_id, c_name) VALUES (56, 'Cepton');
INSERT INTO Company(c_id, c_name) VALUES (57, 'Cerebras Systems');
INSERT INTO Company(c_id, c_name) VALUES (58, 'Ceridian');
INSERT INTO Company(c_id, c_name) VALUES (59, 'Certik');
INSERT INTO Company(c_id, c_name) VALUES (60, 'CGI');
INSERT INTO Company(c_id, c_name) VALUES (61, 'Chisel.ai');
INSERT INTO Company(c_id, c_name) VALUES (62, 'Christie Digital Systems');
INSERT INTO Company(c_id, c_name) VALUES (63, 'CIBC');
INSERT INTO Company(c_id, c_name) VALUES (64, 'Cisco');
INSERT INTO Company(c_id, c_name) VALUES (65, 'Citibank');
INSERT INTO Company(c_id, c_name) VALUES (66, 'Cockroach Labs');
INSERT INTO Company(c_id, c_name) VALUES (67, 'CodeWithChris');
INSERT INTO Company(c_id, c_name) VALUES (68, 'Coherent Logix');
INSERT INTO Company(c_id, c_name) VALUES (69, 'Cohesity');
INSERT INTO Company(c_id, c_name) VALUES (70, 'Coinbase');
INSERT INTO Company(c_id, c_name) VALUES (71, 'Coinsquare');
INSERT INTO Company(c_id, c_name) VALUES (72, 'Compound');
INSERT INTO Company(c_id, c_name) VALUES (73, 'Connected');
INSERT INTO Company(c_id, c_name) VALUES (74, 'Constant Contact');
INSERT INTO Company(c_id, c_name) VALUES (75, 'Core Avionics');
INSERT INTO Company(c_id, c_name) VALUES (76, 'Coursera');
INSERT INTO Company(c_id, c_name) VALUES (77, 'Cover Technologies Inc');
INSERT INTO Company(c_id, c_name) VALUES (78, 'CPP Investments');
INSERT INTO Company(c_id, c_name) VALUES (79, 'Crawford and Co');
INSERT INTO Company(c_id, c_name) VALUES (80, 'Creospark');
INSERT INTO Company(c_id, c_name) VALUES (81, 'Cube Group');
INSERT INTO Company(c_id, c_name) VALUES (82, 'Curinos');
INSERT INTO Company(c_id, c_name) VALUES (83, 'Curvegrid (Japan)');
INSERT INTO Company(c_id, c_name) VALUES (84, 'D2L');
INSERT INTO Company(c_id, c_name) VALUES (85, 'data.world');
INSERT INTO Company(c_id, c_name) VALUES (86, 'Databrick');
INSERT INTO Company(c_id, c_name) VALUES (87, 'Datadog');
INSERT INTO Company(c_id, c_name) VALUES (88, 'Deep Breathe');
INSERT INTO Company(c_id, c_name) VALUES (89, 'Deep Genomics');
INSERT INTO Company(c_id, c_name) VALUES (90, 'Dejero');
INSERT INTO Company(c_id, c_name) VALUES (91, 'Deloitte');
INSERT INTO Company(c_id, c_name) VALUES (92, 'Delphia Asset Management');
INSERT INTO Company(c_id, c_name) VALUES (93, 'Digital Extremes (Marketing)');
INSERT INTO Company(c_id, c_name) VALUES (94, 'Digitaled');
INSERT INTO Company(c_id, c_name) VALUES (95, 'DocuSign');
INSERT INTO Company(c_id, c_name) VALUES (96, 'Draper');
INSERT INTO Company(c_id, c_name) VALUES (97, 'Dreamschools');
INSERT INTO Company(c_id, c_name) VALUES (98, 'Dropbase (Castodia)');
INSERT INTO Company(c_id, c_name) VALUES (99, 'DRW');
INSERT INTO Company(c_id, c_name) VALUES (100, 'Durovac');
INSERT INTO Company(c_id, c_name) VALUES (101, 'Ecobee');
INSERT INTO Company(c_id, c_name) VALUES (102, 'Ecompliance');
INSERT INTO Company(c_id, c_name) VALUES (103, 'Elekta');
INSERT INTO Company(c_id, c_name) VALUES (104, 'Embark Trucks');
INSERT INTO Company(c_id, c_name) VALUES (105, 'Enlighted Inc');
INSERT INTO Company(c_id, c_name) VALUES (106, 'Eon Media');
INSERT INTO Company(c_id, c_name) VALUES (107, 'Equifax D&A');
INSERT INTO Company(c_id, c_name) VALUES (108, 'Equitable Life Insurance Company');
INSERT INTO Company(c_id, c_name) VALUES (109, 'ESCRYPT');
INSERT INTO Company(c_id, c_name) VALUES (110, 'eSentire');
INSERT INTO Company(c_id, c_name) VALUES (111, 'EY');
INSERT INTO Company(c_id, c_name) VALUES (112, 'Facebook');
INSERT INTO Company(c_id, c_name) VALUES (113, 'Faire');
INSERT INTO Company(c_id, c_name) VALUES (114, 'Fleet Complete');
INSERT INTO Company(c_id, c_name) VALUES (115, 'Flex AI');
INSERT INTO Company(c_id, c_name) VALUES (116, 'Flipp');
INSERT INTO Company(c_id, c_name) VALUES (117, 'Float');
INSERT INTO Company(c_id, c_name) VALUES (118, 'Ford');
INSERT INTO Company(c_id, c_name) VALUES (119, 'Forethought AI');
INSERT INTO Company(c_id, c_name) VALUES (120, 'Freshbooks');
INSERT INTO Company(c_id, c_name) VALUES (121, 'Genesys Laboratories');
INSERT INTO Company(c_id, c_name) VALUES (122, 'Geotab');
INSERT INTO Company(c_id, c_name) VALUES (123, 'Get ResQ');
INSERT INTO Company(c_id, c_name) VALUES (124, 'Glu');
INSERT INTO Company(c_id, c_name) VALUES (125, 'Google');
INSERT INTO Company(c_id, c_name) VALUES (126, 'groq (Groq Inc)');
INSERT INTO Company(c_id, c_name) VALUES (127, 'Gsoft');
INSERT INTO Company(c_id, c_name) VALUES (128, 'H2Analytics');
INSERT INTO Company(c_id, c_name) VALUES (129, 'Halp');
INSERT INTO Company(c_id, c_name) VALUES (130, 'Hatch Credit');
INSERT INTO Company(c_id, c_name) VALUES (131, 'HeadSpin');
INSERT INTO Company(c_id, c_name) VALUES (132, 'High Q Technologies');
INSERT INTO Company(c_id, c_name) VALUES (133, 'Hockeystick');
INSERT INTO Company(c_id, c_name) VALUES (134, 'Home Depot (Dev)');
INSERT INTO Company(c_id, c_name) VALUES (135, 'HomeX');
INSERT INTO Company(c_id, c_name) VALUES (136, 'HOOPP (Health Care of Ontario Pension Plan)');
INSERT INTO Company(c_id, c_name) VALUES (137, 'Horizon Studio');
INSERT INTO Company(c_id, c_name) VALUES (138, 'Huawei');
INSERT INTO Company(c_id, c_name) VALUES (139, 'Hubdoc');
INSERT INTO Company(c_id, c_name) VALUES (140, 'HubSpot');
INSERT INTO Company(c_id, c_name) VALUES (141, 'IBM');
INSERT INTO Company(c_id, c_name) VALUES (142, 'Imagine Communications Corp');
INSERT INTO Company(c_id, c_name) VALUES (143, 'Index Exchange');
INSERT INTO Company(c_id, c_name) VALUES (144, 'Inflight');
INSERT INTO Company(c_id, c_name) VALUES (145, 'Information Builders');
INSERT INTO Company(c_id, c_name) VALUES (146, 'Insticator');
INSERT INTO Company(c_id, c_name) VALUES (147, 'Instinet Canada');
INSERT INTO Company(c_id, c_name) VALUES (148, 'Intact Labs');
INSERT INTO Company(c_id, c_name) VALUES (149, 'Integrate.ai');
INSERT INTO Company(c_id, c_name) VALUES (150, 'Intel');
INSERT INTO Company(c_id, c_name) VALUES (151, 'Intuit');
INSERT INTO Company(c_id, c_name) VALUES (152, 'iS5 Communications');
INSERT INTO Company(c_id, c_name) VALUES (153, 'ISARA');
INSERT INTO Company(c_id, c_name) VALUES (154, 'Jane Street');
INSERT INTO Company(c_id, c_name) VALUES (155, 'Jays Care Foundation (TBJ)');
INSERT INTO Company(c_id, c_name) VALUES (156, 'Jobox.ai');
INSERT INTO Company(c_id, c_name) VALUES (157, 'Kaleidascape');
INSERT INTO Company(c_id, c_name) VALUES (158, 'Kambeo');
INSERT INTO Company(c_id, c_name) VALUES (159, 'KeepTruckin');
INSERT INTO Company(c_id, c_name) VALUES (160, 'Kiavi');
INSERT INTO Company(c_id, c_name) VALUES (161, 'Kinaxis');
INSERT INTO Company(c_id, c_name) VALUES (162, 'Kodiak Robotics');
INSERT INTO Company(c_id, c_name) VALUES (163, 'Konrad Group');
INSERT INTO Company(c_id, c_name) VALUES (164, 'LCBO');
INSERT INTO Company(c_id, c_name) VALUES (165, 'League');
INSERT INTO Company(c_id, c_name) VALUES (166, 'Level');
INSERT INTO Company(c_id, c_name) VALUES (167, 'LifeWorks');
INSERT INTO Company(c_id, c_name) VALUES (168, 'Lifion by Adp');
INSERT INTO Company(c_id, c_name) VALUES (169, 'Linkedin');
INSERT INTO Company(c_id, c_name) VALUES (170, 'Loblaw');
INSERT INTO Company(c_id, c_name) VALUES (171, 'Loblaw Digital');
INSERT INTO Company(c_id, c_name) VALUES (172, 'Manulife');
INSERT INTO Company(c_id, c_name) VALUES (173, 'Mastercard Foundation');
INSERT INTO Company(c_id, c_name) VALUES (174, 'Mattermost');
INSERT INTO Company(c_id, c_name) VALUES (175, 'McAfee');
INSERT INTO Company(c_id, c_name) VALUES (176, 'Metrist');
INSERT INTO Company(c_id, c_name) VALUES (177, 'Microart Services');
INSERT INTO Company(c_id, c_name) VALUES (178, 'Microsoft');
INSERT INTO Company(c_id, c_name) VALUES (179, 'Molex');
INSERT INTO Company(c_id, c_name) VALUES (180, 'MotoInsight');
INSERT INTO Company(c_id, c_name) VALUES (181, 'Motorola Solutions');
INSERT INTO Company(c_id, c_name) VALUES (182, 'Moveworks');
INSERT INTO Company(c_id, c_name) VALUES (183, 'NASDAQ');
INSERT INTO Company(c_id, c_name) VALUES (184, 'Newfront Insurance');
INSERT INTO Company(c_id, c_name) VALUES (185, 'Nextroll');
INSERT INTO Company(c_id, c_name) VALUES (186, 'Nissan');
INSERT INTO Company(c_id, c_name) VALUES (187, 'Nokia');
INSERT INTO Company(c_id, c_name) VALUES (188, 'Noom');
INSERT INTO Company(c_id, c_name) VALUES (189, 'Norm Li');
INSERT INTO Company(c_id, c_name) VALUES (190, 'NuraLogix');
INSERT INTO Company(c_id, c_name) VALUES (191, 'Nuro');
INSERT INTO Company(c_id, c_name) VALUES (192, 'Nuvalence');
INSERT INTO Company(c_id, c_name) VALUES (193, 'Nuvation');
INSERT INTO Company(c_id, c_name) VALUES (194, 'Nvidia');
INSERT INTO Company(c_id, c_name) VALUES (195, 'OANDA');
INSERT INTO Company(c_id, c_name) VALUES (196, 'Okta');
INSERT INTO Company(c_id, c_name) VALUES (197, 'OMERS');
INSERT INTO Company(c_id, c_name) VALUES (198, 'Onsemi');
INSERT INTO Company(c_id, c_name) VALUES (199, 'Ontario Institute for Cancer Research');
INSERT INTO Company(c_id, c_name) VALUES (200, 'Ontario Ministry of Health');
INSERT INTO Company(c_id, c_name) VALUES (201, 'OpenText');
INSERT INTO Company(c_id, c_name) VALUES (202, 'OPSEU Pension Trust');
INSERT INTO Company(c_id, c_name) VALUES (203, 'Oracle');
INSERT INTO Company(c_id, c_name) VALUES (204, 'Penfield.AI');
INSERT INTO Company(c_id, c_name) VALUES (205, 'Pepsico');
INSERT INTO Company(c_id, c_name) VALUES (206, 'PlayStation');
INSERT INTO Company(c_id, c_name) VALUES (207, 'PointClickCare');
INSERT INTO Company(c_id, c_name) VALUES (208, 'primer.ai');
INSERT INTO Company(c_id, c_name) VALUES (209, 'Prodigy Education');
INSERT INTO Company(c_id, c_name) VALUES (210, 'Qualcomm (Markham)');
INSERT INTO Company(c_id, c_name) VALUES (211, 'Radix Labs');
INSERT INTO Company(c_id, c_name) VALUES (212, 'RBC');
INSERT INTO Company(c_id, c_name) VALUES (213, 'RBC (Business Analyst)');
INSERT INTO Company(c_id, c_name) VALUES (214, 'RBC (Data Analyst)');
INSERT INTO Company(c_id, c_name) VALUES (215, 'RBC (Risk Management)');
INSERT INTO Company(c_id, c_name) VALUES (216, 'Reebee');
INSERT INTO Company(c_id, c_name) VALUES (217, 'Relay Financial');
INSERT INTO Company(c_id, c_name) VALUES (218, 'Relic Entertainment');
INSERT INTO Company(c_id, c_name) VALUES (219, 'Remitbee (BLACKLISTED!)');
INSERT INTO Company(c_id, c_name) VALUES (220, 'Replicant Inc');
INSERT INTO Company(c_id, c_name) VALUES (221, 'ResQ');
INSERT INTO Company(c_id, c_name) VALUES (222, 'Ritual');
INSERT INTO Company(c_id, c_name) VALUES (223, 'Robinhood');
INSERT INTO Company(c_id, c_name) VALUES (224, 'Roblox');
INSERT INTO Company(c_id, c_name) VALUES (225, 'Rocscience');
INSERT INTO Company(c_id, c_name) VALUES (226, 'Rogers');
INSERT INTO Company(c_id, c_name) VALUES (227, 'Sagen');
INSERT INTO Company(c_id, c_name) VALUES (228, 'Samsung Research America');
INSERT INTO Company(c_id, c_name) VALUES (229, 'SAP');
INSERT INTO Company(c_id, c_name) VALUES (230, 'SAP ML');
INSERT INTO Company(c_id, c_name) VALUES (231, 'Scotiabank');
INSERT INTO Company(c_id, c_name) VALUES (232, 'Scrawlr');
INSERT INTO Company(c_id, c_name) VALUES (233, 'Shinydocs');
INSERT INTO Company(c_id, c_name) VALUES (234, 'Shopify');
INSERT INTO Company(c_id, c_name) VALUES (235, 'Shoplogic');
INSERT INTO Company(c_id, c_name) VALUES (236, 'Sibros');
INSERT INTO Company(c_id, c_name) VALUES (237, 'SideFX');
INSERT INTO Company(c_id, c_name) VALUES (238, 'Simplii Financial');
INSERT INTO Company(c_id, c_name) VALUES (239, 'Skydio');
INSERT INTO Company(c_id, c_name) VALUES (240, 'Smile CDR');
INSERT INTO Company(c_id, c_name) VALUES (241, 'Snap Inc');
INSERT INTO Company(c_id, c_name) VALUES (242, 'Snowflake computing');
INSERT INTO Company(c_id, c_name) VALUES (243, 'Solana Labs');
INSERT INTO Company(c_id, c_name) VALUES (244, 'SoundHound');
INSERT INTO Company(c_id, c_name) VALUES (245, 'SPS Commerce');
INSERT INTO Company(c_id, c_name) VALUES (246, 'Square');
INSERT INTO Company(c_id, c_name) VALUES (247, 'Squaredance');
INSERT INTO Company(c_id, c_name) VALUES (248, 'Squarepoint Capital');
INSERT INTO Company(c_id, c_name) VALUES (249, 'SS&C Technologies');
INSERT INTO Company(c_id, c_name) VALUES (250, 'Stablecorp');
INSERT INTO Company(c_id, c_name) VALUES (251, 'Stackadapt');
INSERT INTO Company(c_id, c_name) VALUES (252, 'Standardbio Tools');
INSERT INTO Company(c_id, c_name) VALUES (253, 'Stealth Startup');
INSERT INTO Company(c_id, c_name) VALUES (254, 'Stratum ai');
INSERT INTO Company(c_id, c_name) VALUES (255, 'Super (Snapcommerce)');
INSERT INTO Company(c_id, c_name) VALUES (256, 'Sync.com');
INSERT INTO Company(c_id, c_name) VALUES (257, 'System 1');
INSERT INTO Company(c_id, c_name) VALUES (258, 'Tactic Studios');
INSERT INTO Company(c_id, c_name) VALUES (259, 'Tailscale');
INSERT INTO Company(c_id, c_name) VALUES (260, 'TD');
INSERT INTO Company(c_id, c_name) VALUES (261, 'Tealbook');
INSERT INTO Company(c_id, c_name) VALUES (262, 'Teledyne Dalsa');
INSERT INTO Company(c_id, c_name) VALUES (263, 'Tesla');
INSERT INTO Company(c_id, c_name) VALUES (264, 'Texada Software');
INSERT INTO Company(c_id, c_name) VALUES (265, 'TextNow');
INSERT INTO Company(c_id, c_name) VALUES (266, 'The Co-operators');
INSERT INTO Company(c_id, c_name) VALUES (267, 'The Cooperators');
INSERT INTO Company(c_id, c_name) VALUES (268, 'The Empire Life Insurance Company');
INSERT INTO Company(c_id, c_name) VALUES (269, 'The Flight Deck');
INSERT INTO Company(c_id, c_name) VALUES (270, 'theScore');
INSERT INTO Company(c_id, c_name) VALUES (271, 'Thomson Reuters');
INSERT INTO Company(c_id, c_name) VALUES (272, 'Thumbtack');
INSERT INTO Company(c_id, c_name) VALUES (273, 'TikTok');
INSERT INTO Company(c_id, c_name) VALUES (274, 'Titanium Agency');
INSERT INTO Company(c_id, c_name) VALUES (275, 'TOOLBX');
INSERT INTO Company(c_id, c_name) VALUES (276, 'Toronto Transit Commission');
INSERT INTO Company(c_id, c_name) VALUES (277, 'Toyota Motor Manufacturing Canada');
INSERT INTO Company(c_id, c_name) VALUES (278, 'Trexo Robotics');
INSERT INTO Company(c_id, c_name) VALUES (279, 'Tribalscale');
INSERT INTO Company(c_id, c_name) VALUES (280, 'Trustwave Holdings');
INSERT INTO Company(c_id, c_name) VALUES (281, 'Tulip Retail');
INSERT INTO Company(c_id, c_name) VALUES (282, 'TutorOcean');
INSERT INTO Company(c_id, c_name) VALUES (283, 'Tweepsmap');
INSERT INTO Company(c_id, c_name) VALUES (284, 'Twitter');
INSERT INTO Company(c_id, c_name) VALUES (285, 'Uber');
INSERT INTO Company(c_id, c_name) VALUES (286, 'Ubisoft');
INSERT INTO Company(c_id, c_name) VALUES (287, 'UHN (DATA Team)');
INSERT INTO Company(c_id, c_name) VALUES (288, 'Ultimate Software');
INSERT INTO Company(c_id, c_name) VALUES (289, 'Union Bank of Switzerland (UBS Group AG)');
INSERT INTO Company(c_id, c_name) VALUES (290, 'Untether AI');
INSERT INTO Company(c_id, c_name) VALUES (291, 'Uplift');
INSERT INTO Company(c_id, c_name) VALUES (292, 'Veeva Systems');
INSERT INTO Company(c_id, c_name) VALUES (293, 'Vendia');
INSERT INTO Company(c_id, c_name) VALUES (294, 'Veriday');
INSERT INTO Company(c_id, c_name) VALUES (295, 'Versa Networks');
INSERT INTO Company(c_id, c_name) VALUES (296, 'Versett');
INSERT INTO Company(c_id, c_name) VALUES (297, 'VerticalScope');
INSERT INTO Company(c_id, c_name) VALUES (298, 'Vidyard');
INSERT INTO Company(c_id, c_name) VALUES (299, 'Voiceform');
INSERT INTO Company(c_id, c_name) VALUES (300, 'Waabi Innovation');
INSERT INTO Company(c_id, c_name) VALUES (301, 'Wattpad');
INSERT INTO Company(c_id, c_name) VALUES (302, 'Wayfair');
INSERT INTO Company(c_id, c_name) VALUES (303, 'Wealthsimple');
INSERT INTO Company(c_id, c_name) VALUES (304, 'Wind River');
INSERT INTO Company(c_id, c_name) VALUES (305, 'Wish');
INSERT INTO Company(c_id, c_name) VALUES (306, 'WSIB Innovation Lab');
INSERT INTO Company(c_id, c_name) VALUES (307, 'Xanadu');
INSERT INTO Company(c_id, c_name) VALUES (308, 'Yext');
INSERT INTO Company(c_id, c_name) VALUES (309, 'Zenreach/Greenfield');
INSERT INTO Company(c_id, c_name) VALUES (310, 'Zighra');
