INSERT INTO Prog(p_id, prog_name) VALUES (25, 'Accounting & Financial Management');
INSERT INTO Prog(p_id, prog_name) VALUES (2, 'Actuarial Science');
INSERT INTO Prog(p_id, prog_name) VALUES (3, 'Applied Mathematics');
INSERT INTO Prog(p_id, prog_name) VALUES (4, 'Biostatistics');
INSERT INTO Prog(p_id, prog_name) VALUES (20, 'Chemical Engineering');
INSERT INTO Prog(p_id, prog_name) VALUES (1, 'Combinatorics and Optimization');
INSERT INTO Prog(p_id, prog_name) VALUES (5, 'Computational Mathematics');
INSERT INTO Prog(p_id, prog_name) VALUES (17, 'Computer Engineering');
INSERT INTO Prog(p_id, prog_name) VALUES (27, 'Computer Science');
INSERT INTO Prog(p_id, prog_name) VALUES (26, 'Computing & Financial Management');
INSERT INTO Prog(p_id, prog_name) VALUES (6, 'Data Science');
INSERT INTO Prog(p_id, prog_name) VALUES (22, 'Electrical Engineering');
INSERT INTO Prog(p_id, prog_name) VALUES (28, 'FARM');
INSERT INTO Prog(p_id, prog_name) VALUES (23, 'Management Engineering');
INSERT INTO Prog(p_id, prog_name) VALUES (7, 'Mathematical Economics');
INSERT INTO Prog(p_id, prog_name) VALUES (8, 'Mathematical Finance');
INSERT INTO Prog(p_id, prog_name) VALUES (9, 'Mathematical Optimization');
INSERT INTO Prog(p_id, prog_name) VALUES (10, 'Mathematical Physics');
INSERT INTO Prog(p_id, prog_name) VALUES (11, 'Mathematical Studies');
INSERT INTO Prog(p_id, prog_name) VALUES (14, 'Mathematics/Teaching');
INSERT INTO Prog(p_id, prog_name) VALUES (19, 'Mechanical Engineering');
INSERT INTO Prog(p_id, prog_name) VALUES (18, 'Mechatronics Engineering');
INSERT INTO Prog(p_id, prog_name) VALUES (24, 'Other Engineering');
INSERT INTO Prog(p_id, prog_name) VALUES (15, 'Other Math');
INSERT INTO Prog(p_id, prog_name) VALUES (30, 'Other Progs - Contact Sys Admin to be added');
INSERT INTO Prog(p_id, prog_name) VALUES (29, 'Other Science - Contact Sys Admin to be added');
INSERT INTO Prog(p_id, prog_name) VALUES (12, 'Pure Mathematics');
INSERT INTO Prog(p_id, prog_name) VALUES (16, 'Software Engineering');
INSERT INTO Prog(p_id, prog_name) VALUES (13, 'Statistics');
INSERT INTO Prog(p_id, prog_name) VALUES (21, 'System Design Engineering');
